version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: container_name
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
